module-info instead of Automatic-Module-Name
It is necessary to upgrade maven-surefire-plugin, otherwise
Using maven-surefire-plugin 2.22.2 on jdk 8 you will get
`NoClassDefFoundError: groovy/lang/GroovyObject`.